### PR TITLE
Add example script to load all projects into TF files

### PR DESCRIPTION
**Pull request by fdegier**
This PR adds a script that will allow users to easily generate a repository with all the TF files, the documentation describes how to use it.

### CODE REVIEW

**Comment by fdegier** [comment]
@cmcarthur please see this PR as discussed during our call.

**Comment by b-per** [comment]
Thanks for raising this!

I will have a closer look when I have some time to dig further.

We can have a Python script but I guess that ideally we could also have a new command added to the Go program to perform the same task. (I will check if it wouldn't take too much effort to rewrite the same feature)

**Comment by b-per** [comment]
I've had a first look.

Is it correct that what you wanted to achieve with this script was too:
- generate "the linked config" for all the available resources in the dbt Cloud account
- output one terraform file per dbt Cloud project


If so, I am thinking that I could add the following features to the tool:
- allowing `all` for `--resource-types` so that we would loop through all the available resources
- allowing outputting to different `tf` files for the different projects
  - we'll have some issues for the "global" resources that are not tied to just 1 project, like notifications, or groups but I can think of a way to handle it

**Comment by fdegier** [comment]
Thanks. 


>* generate "the linked config" for all the available resources in the dbt Cloud account

Correct, I wanted 1 script that would get the entire state for DBT cloud in the account, this was a specific requirements as we needed to migrated to another account. 


> * output one terraform file per dbt Cloud project

Correct as this makes it easiest for my clients to manage their projects. 


> * allowing `all` for `--resource-types` so that we would loop through all the available resources

That would work 

> * allowing outputting to different `tf` files for the different projects

One challenge I had here was that if one of the TF files becomes incorrect, the script broke as it seemed to check the state of the entire directory. 

>  * we'll have some issues for the "global" resources that are not tied to just 1 project, like notifications, or groups but I can think of a way to handle it

What I did was first create the global resources and then run the projects.

**Pull request closed without merging**
